import Link from "next/link";
import VideoBackground from "./experiences/video-bg";
import { useRef } from "react";
import { useEffect } from "react";
import HeroPicture from "./hero-picture";

// The "Experience soul" watercolour — desktop art from 768 px, the phone art
// below — through the home banner's <picture> (hero-picture.jsx): one download
// per device, AVIF / WebP / JPEG pre-generated by
// scripts/optimize-static-images.mjs (quality measured per width), and a
// light-grey box of the art's own proportions so nothing shifts when it paints. It replaces
// two `priority` + `unoptimized` next/image elements that preloaded BOTH
// full-size JPEGs (800 KB) on every device and reserved the wrong height.
const GEN = "/images/experiences/gen";
const set = (name, widths, ext) => widths.map((w) => `${GEN}/${name}-${w}.${ext} ${w}w`).join(", ");
const DESKTOP_WIDTHS = [960, 1280, 1600];
const MOBILE_WIDTHS = [640, 960, 1280, 1600];
const EXPERIENCES_ART = Object.freeze({
  isStatic: true,
  alt: "Experience soul: a watercolour of India with Kedarnath and Badrinath temples, the Statue of Unity, golden temples, a tiger, desert camels and a beach",
  desktop: { avif: set("banner", DESKTOP_WIDTHS, "avif"), webp: set("banner", DESKTOP_WIDTHS, "webp"), jpeg: set("banner", DESKTOP_WIDTHS, "jpeg"), width: 1600, height: 843 },
  mobile: { avif: set("mobile-banner", MOBILE_WIDTHS, "avif"), webp: set("mobile-banner", MOBILE_WIDTHS, "webp"), jpeg: set("mobile-banner", MOBILE_WIDTHS, "jpeg"), width: 1600, height: 2176 },
});

export function ExpHero() {
  // return (
  //   <section className="relative h-[500px] md:h-[80vh]  w-full">
  //     {/* <VideoBackground /> */}
  //     <div className="relative w-full overflow-hidden rounded-xl pt-20">
  //       <iframe
  //         className="absolute top-0 left-0 h-full w-full"
  //         src="https://www.youtube.com/embed/T-kulebBnxg?autoplay=1&mute=1&loop=1&playlist=T-kulebBnxg&controls=0&showinfo=0&modestbranding=1&rel=0"
  //         title="YouTube video player"
  //         frameborder="0"
  //         allow="autoplay; encrypted-media; picture-in-picture"
  //         referrerpolicy="strict-origin-when-cross-origin"
  //         allowfullscreen
  //       ></iframe>
  //     </div>
  //     <div className="mobile:mt-20 relative h-full px-4 sm:px-6 md:px-[72px] py-8 sm:py-12 md:py-[128px] flex flex-col items-center justify-center">
  //       <h1 className="text-2xl font-bricolage sm:text-3xl md:text-5xl font-bold text-white text-center mb-2 sm:mb-4">
  //         Discover Thrilling Experiences in India
  //       </h1>
  //       <p className="text-sm sm:text-base md:text-lg text-white/90 text-center mb-4 sm:mb-8">
  //         Explore exciting activities and create unforgettable memories
  //       </p>

  //       <Link
  //         href={"#experiences"}
  //         className="border bg-[#444]/30 backdrop-blur-md text-white border-[#eee]/30 hover:ring-2 hover:ring-white mb-6 sm:mb-8 md:mb-12 px-3 sm:px-4 py-1.5 sm:py-2 rounded-3xl text-sm sm:text-base"
  //         onClick={() => {}}
  //       >
  //         Book Your Experience
  //       </Link>
  //     </div>
  //   </section>
  // );
  const playerRef = useRef(null);

  // useEffect(() => {
  //   let player;

  //   const initPlayer = () => {
  //     if (playerRef.current) {
  //       playerRef.current.destroy();
  //     }

  //     playerRef.current = new window.YT.Player("yt-player", {
  //       videoId: "T-kulebBnxg",
  //       playerVars: {
  //         autoplay: 1,
  //         mute: 1,
  //         controls: 0,
  //         modestbranding: 1,
  //         rel: 0,
  //         playsinline: 1,
  //         start: 10,
  //         end: 88,
  //       },
  //       events: {
  //         onReady: (e) => {
  //           e.target.mute();
  //           e.target.seekTo(10);
  //           e.target.playVideo();
  //         },
  //         onStateChange: (e) => {
  //           if (e.data === window.YT.PlayerState.ENDED) {
  //             e.target.seekTo(10);
  //             e.target.playVideo();
  //           }
  //         },
  //       },
  //     });
  //   };

  //   // ✅ If YT already loaded → init immediately
  //   if (window.YT && window.YT.Player) {
  //     initPlayer();
  //   } else {
  //     // Load API once
  //     const tag = document.createElement("script");
  //     tag.src = "https://www.youtube.com/iframe_api";
  //     document.body.appendChild(tag);

  //     window.onYouTubeIframeAPIReady = initPlayer;
  //   }

  //   // ✅ Cleanup on route change
  //   return () => {
  //     if (playerRef.current) {
  //       playerRef.current.destroy();
  //       playerRef.current = null;
  //     }
  //   };
  // }, []);

  return (
    <section className="relative mt-24 md:mt-0 w-full overflow-hidden">
      <div className="w-full">
        <HeroPicture hero={EXPERIENCES_ART} fallback={EXPERIENCES_ART} boxClassName="aspect-[2000/2720] md:aspect-[1600/843]" />
      </div>
    </section>
  );
}
